addSbtPlugin("com.jsuereth"       % "sbt-pgp"                       % "1.1.2")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject"      % "0.6.1")
addSbtPlugin("org.portable-scala" % "sbt-scala-native-crossproject" % "0.6.1")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"                   % "0.6.32")
addSbtPlugin("org.scala-native"   % "sbt-scala-native"              % "0.3.9")
addSbtPlugin("com.eed3si9n"       % "sbt-sriracha"                  % "0.1.0")
addSbtPlugin("ch.epfl.lamp"       % "sbt-dotty"                     % "0.3.4")
